# Generated by Django 5.1.2 on 2024-12-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_adquicicion', models.DateField()),
                ('num_placa_almacen', models.CharField(default='placa', max_length=45, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default='00000', max_digits=20, max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.category')),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.subcategory')),
            ],
        ),
    ]
