# Generated by Django 5.1.2 on 2024-12-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_moviliario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviliario',
            old_name='fecha_adquicicion',
            new_name='ad_date',
        ),
        migrations.RenameField(
            model_name='moviliario',
            old_name='descripcion',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='moviliario',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='moviliario',
            old_name='precio',
            new_name='price',
        ),
    ]
