# Generated by Django 5.1.2 on 2024-12-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_rename_fecha_adquicicion_moviliario_ad_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviliario',
            name='sub_cat',
        ),
    ]
