# Generated by Django 5.1.2 on 2024-12-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_remove_moviliario_sub_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.regional')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('direct', models.CharField(max_length=255)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.regional')),
            ],
        ),
    ]
