# Generated by Django 5.1.2 on 2024-12-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_regional_centroformacion_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prog', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hours', models.IntegerField()),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ficha', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('etapa', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.programa_formacion')),
            ],
        ),
    ]
