# Generated by Django 5.1.2 on 2024-12-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_programa_formacion_ficha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='nombre',
            new_name='name',
        ),
    ]
